spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kdt
    username: blessing333
    password: 12345678
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  error:
    include-exception: true
    include-message: always
