 spring:
   profiles:
     active: local
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kdt
    username: blessing333
    password: 12345678
---
spring:
 profiles:
   active: default
 datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   username: sa